/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.3.4
 * Product:       sfm3505
 * Model-Version: 1.2.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sfm3505_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

static uint8_t communication_buffer[18] = {0};

static uint8_t _i2c_address;

void sfm3505_init(uint8_t i2c_address) {
    _i2c_address = i2c_address;
}

uint32_t sfm3505_signal_o2_flow_raw(const uint8_t* flow_bytes_raw) {
    uint32_t o2_flow_raw = 0;
    o2_flow_raw = (uint32_t)((flow_bytes_raw[3] << 16) |
                             (flow_bytes_raw[4] << 8) | flow_bytes_raw[5]);
    return o2_flow_raw;
}

uint32_t sfm3505_signal_air_flow_raw(const uint8_t* flow_bytes_raw) {
    uint32_t air_flow_raw = 0;
    air_flow_raw = (uint32_t)((flow_bytes_raw[0] << 16) |
                              (flow_bytes_raw[1] << 8) | flow_bytes_raw[2]);
    return air_flow_raw;
}

int16_t sfm3505_read_all_measurement_data_no_float(uint32_t* a_air_flow_raw,
                                                   uint32_t* a_o2_flow_raw) {
    uint8_t flow_bytes_raw[6] = {0};
    int16_t local_error = 0;
    local_error = sfm3505_read_all_measurement_data_raw(flow_bytes_raw, 6);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *a_air_flow_raw = sfm3505_signal_air_flow_raw((uint8_t*)(flow_bytes_raw));
    *a_o2_flow_raw = sfm3505_signal_o2_flow_raw((uint8_t*)(flow_bytes_raw));
    return local_error;
}

int16_t sfm3505_read_air_measurement_data_no_float(uint32_t* a_air_flow_raw) {
    uint8_t flow_bytes_raw[4] = {0};
    int16_t local_error = 0;
    local_error = sfm3505_read_air_measurement_data_raw(flow_bytes_raw, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *a_air_flow_raw = sfm3505_signal_air_flow_raw((uint8_t*)(flow_bytes_raw));

    return local_error;
}

int16_t sfm3505_start_continuous_measurement() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3603);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(4 * 1000);
    return local_error;
}

int16_t sfm3505_start_continuous_measurement_with_filter(uint16_t a_filter) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3603);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(buffer_ptr,
                                                        local_offset, a_filter);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(4 * 1000);
    return local_error;
}

int16_t
sfm3505_read_all_measurement_data_raw(uint8_t* all_flow_bytes_raw,
                                      uint16_t all_flow_bytes_raw_size) {
    int16_t local_error = NO_ERROR;
    uint8_t buffer_ptr[9] = {0};
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 6);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)all_flow_bytes_raw,
                                all_flow_bytes_raw_size);
    return local_error;
}

int16_t
sfm3505_read_air_measurement_data_raw(uint8_t* air_flow_bytes_raw,
                                      uint16_t air_flow_bytes_raw_size) {
    int16_t local_error = NO_ERROR;
    uint8_t buffer_ptr[6] = {0};
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 4);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)air_flow_bytes_raw,
                                air_flow_bytes_raw_size);
    return local_error;
}

int16_t sfm3505_stop_continuous_measurement() {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x3ff9);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    return local_error;
}

int16_t sfm3505_configure_averaging(uint16_t average_window) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x364d);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        buffer_ptr, local_offset, average_window);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    return local_error;
}

int16_t sfm3505_read_product_identifier(uint32_t* product_identifier,
                                        uint64_t* serial_number) {
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command16_to_buffer(buffer_ptr, local_offset, 0x365b);
    local_error =
        sensirion_i2c_write_data(_i2c_address, buffer_ptr, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    local_error = sensirion_i2c_read_data_inplace(_i2c_address, buffer_ptr, 12);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *product_identifier = sensirion_common_bytes_to_uint32_t(&buffer_ptr[0]);
    sensirion_common_to_integer(&buffer_ptr[4], (uint8_t*)serial_number,
                                LONG_INTEGER, 8);
    return local_error;
}
